---
- hosts: servers
  become: yes
  roles:
    - role: packages
    - role: docker

#- hosts: nexussrv
#  become: yes
#  roles:
#    - role: nexus

- hosts: jenkinssrv
  become: yes
  roles:
    - role: jenkins

#- hosts: slavesrv
#  become: yes
#  roles:
#    - role: docker
#    - role: slave
