---
- hosts: servers
  become: yes
  roles:
    - role: packages
      tags: packages

- hosts: nexussrv
  become: yes
  roles:
    - role: nexus
      tags: nexus

- hosts: jenkinssrv
  become: yes
  roles:
    - role: jenkins
      tags: jenkins

- hosts: slavesrv
  become: yes
  roles:
    - role: slave
      tags: slave
