---
# Docker packages list
packages_docker:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'containerd.io'

# Insecure registry addresses
docker_insecure_registry_addresses:
  - '31.41.156.90:8123'
  - '31.41.156.90:8124'
