---
  - name: Add jenkins user
    user:
      name: jenkins
      home: /var/lib/jenkins
      shell: /bin/bash
  - name: Set up autorized_keys
    authorized_key:
      user: jenkins
      state: present
      key: "{{ lookup('file', 'files/id_rsa.pub') }}"
  - name: ensure pass and gnupg is present, needed for slave
    apt: 
      pkg:
        - pass
        - gnupg2
      state: present
      update_cache: yes