---
  - name: Add jenkins user
    user:
      name: jenkins
      home: /var/lib/jenkins
      shell: /bin/bash
  - name: Set up autorized_keys
    authorized_key:
      user: jenkins
      state: present
      key: "{{ lookup('file', 'files/id_rsa.pub') }}"
  - name: ensure Java is present
    apt:
      name: openjdk-8-jdk 
      state: present
  - name: ensure Maven is present
    apt: 
      name: maven
      state: present
      update_cache: yes