---
- name: Add apt key for docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' 
    state: present
    filename: docker

- name: ensure docker is installed
  apt:
    name: "{{ packages_docker }}"
    state: present
    update_cache: yes
  notify:
    - restart docker

- name: ensure docker config dir exists
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy daemon.json for insecure registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart docker
